export enum TRANSACTION_NAMES {
	CheckLogin = 'enrollCheckLogin',
	CreateLogin = 'createLogin',
	FindPerson = 'findPerson',
	CreatePerson = 'createPerson',
	UploadDocument = 'UploadDocument',
	UploadDocumentsById = 'UploadDocumentsById',
	CreateVerificationCode = 'CreateVerificationCode',
	UpdatePhone = 'UpdatePhone',
	UpdateAddress = 'UpdateAddress',
	FetchPriemFilials = 'FetchPriemFilials',
	FetchPriemInstitutes = 'FetchPriemInstitutes',
	FetchPriemEducationLevels = 'FetchPriemEducationLevels',
	FetchPriemDirections = 'FetchPriemDirections',
	FetchPriemProfiles = 'FetchPriemProfiles',
	FetchPriemPayForms = 'FetchPriemPayForms',
	FetchPriemEducationForms = 'FetchPriemEducationForms',
	CreatePriemApplication = 'CreatePriemApplication',
	FetchPriemGroups = 'FetchPriemGroups',
}
