export enum TRANSACTION_NAMES {
	CheckLogin = 'CHECK_LOGIN',
	CreateLogin = 'CREATE_LOGIN',
	FindPerson = 'FIND_PERSON',
	CreatePerson = 'CREATE_PERSON',
	UploadDocument = 'UPLOAD_DOCUMENT',
	CreateVerificationCode = 'CREATE_VER_CODE',
	UpdatePhone = 'UPDATE_PHONE',
	UpdateAddress = 'UPDATE_ADDRESS',
	FetchPriemFilials = 'FETCH_PRIEM_FILIALS',
	FetchPriemInstitutes = 'FETCH_PRIEM_INSTS',
	FetchPriemEducationLevels = 'FETCH_EDUC_LEVELS',
	FetchPriemDirections = 'FETCH_PRIEM_DIRECTIONS',
	FetchPriemProfiles = 'FETCH_PRIEM_PROFILES',
	FetchPriemPayForms = 'FETCH_PRIEM_PAY_FORMS',
	FetchPriemEducationForms = 'FETCH_PRIEM_EDUC_FORMS',
	CreateApplication = 'CREATE_APP',
	FetchPriemGroups = 'FETCH_PRIEM_GROUPS',
	PriemLogout = 'PRIEM_LOGOUT',
	VER_PERSON = 'VER_PERSON',
	VER_CONTACTS_PERSON = 'VER_CONTACTS_PERSON',
	SET_EXIST_PERSON_VER_CODE = 'SET_EXIST_PERSON_VER_CODE',
}
