export enum TRANSACTION_NAMES {
	CheckLogin = 'CHECK_LOGIN',
	CreateLogin = 'CREATE_LOGIN',
	FindPerson = 'FIND_PERSON',
	CreatePerson = 'CREATE_PERSON',
	UploadDocument = 'UploadDocument',
	UploadDocumentsById = 'UploadDocumentsById',
	CreateVerificationCode = 'CREATE_VER_CODE',
	UpdatePhone = 'UpdatePhone',
	UpdateAddress = 'UpdateAddress',
	FetchPriemFilials = 'FetchPriemFilials',
	FetchPriemInstitutes = 'FetchPriemInstitutes',
	FetchPriemEducationLevels = 'FetchPriemEducationLevels',
	FetchPriemDirections = 'FetchPriemDirections',
	FetchPriemProfiles = 'FetchPriemProfiles',
	FetchPriemPayForms = 'FetchPriemPayForms',
	FetchPriemEducationForms = 'FetchPriemEducationForms',
	CreatePriemApplication = 'CreatePriemApplication',
	FetchPriemGroups = 'FetchPriemGroups',
}
