export enum EDictionaryNameList {
	FirstNames = 'directory_doc_first_names',
	MiddleNames = 'directory_doc_middle_names',
	PersonDocTypes = 'directory_doc_subtypes_person_doc',
	CoolnessTypes = 'directory_coolness_types',
	EducationDocTypes = 'directory_doc_subtypes_education_doc',
	Governments = 'directory_goverments',
	PreviousEducation = 'directory_prev_educations',
	PriemDepartments = 'directory_departments',
	PriemFilials = 'directory_filial',
	PriemUniversities = 'directory_inst',
	PriemDirections = 'directory_directions',
	PriemProfiles = 'directory_prof',
	PriemFormEducation = 'directory_form_education',
	PriemLevelEducation = 'directory_education_level',
	PriemPaySources = 'directory_financial_sources',
}
